using System.Collections.Generic;
using Model.Entities;

namespace Model.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Model.WebContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(Model.WebContext context)
        {
            new List<Album>
            {
                new Album { Title = "The Best Of Men At Work", Genre = "Rock", Price = 8.99M, Artist =  "Men At Work", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Copland Celebration, Vol. I", Genre = "Classical", Price = 8.99M, Artist =  "Aaron Copland & London Symphony Orchestra", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Worlds", Genre = "Jazz", Price = 8.99M, Artist =  "Aaron Goldberg", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "For Those About To Rock We Salute You", Genre = "Rock", Price = 8.99M, Artist =  "AC/DC", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Let There Be Rock", Genre = "Rock", Price = 8.99M, Artist =  "AC/DC", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Balls to the Wall", Genre = "Rock", Price = 8.99M, Artist =  "Accept", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Restless and Wild", Genre = "Rock", Price = 8.99M, Artist =  "Accept", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Górecki: Symphony No. 3", Genre = "Classical", Price = 8.99M, Artist =  "Adrian Leaper & Doreen de Feis", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Big Ones", Genre = "Rock", Price = 8.99M, Artist =  "Aerosmith", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Quiet Songs", Genre = "Jazz", Price = 8.99M, Artist =  "Aisha Duo", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Jagged Little Pill", Genre = "Rock", Price = 8.99M, Artist =  "Alanis Morissette", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Facelift", Genre = "Rock", Price = 8.99M, Artist =  "Alice In Chains", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Frank", Genre =  "Pop", Price = 8.99M, Artist =  "Amy Winehouse", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ring My Bell", Genre =  "Disco", Price = 8.99M, Artist =  "Anita Ward", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chill: Brazil (Disc 2)", Genre = "Latin", Price = 8.99M, Artist =  "Antônio Carlos Jobim", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Warner 25 Anos", Genre = "Jazz", Price = 8.99M, Artist =  "Antônio Carlos Jobim", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Plays Metallica By Four Cellos", Genre = "Metal", Price = 8.99M, Artist =  "Apocalyptica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Revelations", Genre =  "Alternative", Price = 8.99M, Artist =  "Audioslave", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Audioslave", Genre = "Rock", Price = 8.99M, Artist =  "Audioslave", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Last Night of the Proms", Genre = "Classical", Price = 8.99M, Artist =  "Barry Wordsworth & BBC Concert Orchestra", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Sibelius: Finlandia", Genre = "Classical", Price = 8.99M, Artist =  "Berliner Philharmoniker & Hans Rosbaud", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mozart: Symphonies Nos. 40 & 41", Genre = "Classical", Price = 8.99M, Artist =  "Berliner Philharmoniker & Herbert Von Karajan", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best Of Billy Cobham", Genre = "Jazz", Price = 8.99M, Artist =  "Billy Cobham", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Alcohol Fueled Brewtality Live! [Disc 1]", Genre = "Metal", Price = 8.99M, Artist =  "Black Label Society", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Alcohol Fueled Brewtality Live! [Disc 2]", Genre = "Metal", Price = 8.99M, Artist =  "Black Label Society", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Black Sabbath Vol. 4 (Remaster)", Genre = "Metal", Price = 8.99M, Artist =  "Black Sabbath", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Black Sabbath", Genre = "Metal", Price = 8.99M, Artist =  "Black Sabbath", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Carmina Burana", Genre = "Classical", Price = 8.99M, Artist =  "Boston Symphony Orchestra & Seiji Ozawa", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Soprano Inspired", Genre = "Classical", Price = 8.99M, Artist =  "Britten Sinfonia, Ivor Bolton & Lesley Garrett", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chemical Wedding", Genre = "Metal", Price = 8.99M, Artist =  "Bruce Dickinson", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Prenda Minha", Genre = "Latin", Price = 8.99M, Artist =  "Caetano Veloso", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Sozinho Remix Ao Vivo", Genre = "Latin", Price = 8.99M, Artist =  "Caetano Veloso", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Cake: B-Sides and Rarities", Genre =  "Alternative", Price = 8.99M, Artist =  "Cake", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Carried to Dust (Bonus Track Version)", Genre =  "Alternative", Price = 8.99M, Artist =  "Calexico", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Cássia Eller - Sem Limite [Disc 1]", Genre = "Latin", Price = 8.99M, Artist =  "Cássia Eller", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Le Freak", Genre =  "Disco", Price = 8.99M, Artist =  "Chic", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Scheherazade", Genre = "Classical", Price = 8.99M, Artist =  "Chicago Symphony Orchestra & Fritz Reiner", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Minha Historia", Genre = "Latin", Price = 8.99M, Artist =  "Chico Buarque", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Afrociberdelia", Genre = "Latin", Price = 8.99M, Artist =  "Chico Science & Nação Zumbi", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Da Lama Ao Caos", Genre = "Latin", Price = 8.99M, Artist =  "Chico Science & Nação Zumbi", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Carry On", Genre =  "Alternative", Price = 8.99M, Artist =  "Chris Cornell", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "SCRIABIN: Vers la flamme", Genre = "Classical", Price = 8.99M, Artist =  "Christopher O'Riley", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Acústico MTV [Live]", Genre = "Reggae", Price = 8.99M, Artist =  "Cidade Negra", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Cidade Negra - Hits", Genre = "Reggae", Price = 8.99M, Artist =  "Cidade Negra", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Na Pista", Genre = "Latin", Price = 8.99M, Artist =  "Cláudio Zoli", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chronicle, Vol. 1", Genre = "Rock", Price = 8.99M, Artist =  "Creedence Clearwater Revival", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chronicle, Vol. 2", Genre = "Rock", Price = 8.99M, Artist =  "Creedence Clearwater Revival", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Into The Light", Genre = "Rock", Price = 8.99M, Artist =  "David Coverdale", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Come Taste The Band", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Deep Purple In Rock", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Fireball", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Machine Head", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "MK III The Final Concerts [Disc 1]", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Purpendicular", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Slaves And Masters", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Stormbringer", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Battle Rages On", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Final Concerts (Disc 2)", Genre = "Rock", Price = 8.99M, Artist =  "Deep Purple", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Outbreak", Genre = "Jazz", Price = 8.99M, Artist =  "Dennis Chambers", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Djavan Ao Vivo - Vol. 02", Genre = "Latin", Price = 8.99M, Artist =  "Djavan", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Djavan Ao Vivo - Vol. 1", Genre = "Latin", Price = 8.99M, Artist =  "Djavan", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "MacArthur Park Suite", Genre =  "Disco", Price = 8.99M, Artist =  "Donna Summer", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Un-Led-Ed", Genre = "Rock", Price = 8.99M, Artist =  "Dread Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best of Ed Motta", Genre = "Latin", Price = 8.99M, Artist =  "Ed Motta", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Adams, John: The Chairman Dances", Genre = "Classical", Price = 8.99M, Artist =  "Edo de Waart & San Francisco Symphony", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Elis Regina-Minha História", Genre = "Latin", Price = 8.99M, Artist =  "Elis Regina", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Pachelbel: Canon & Gigue", Genre = "Classical", Price = 8.99M, Artist =  "English Concert & Trevor Pinnock", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Unplugged", Genre = "Latin", Price = 8.99M, Artist =  "Eric Clapton", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Cream Of Clapton", Genre = "Blues", Price = 8.99M, Artist =  "Eric Clapton", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Unplugged", Genre = "Blues", Price = 8.99M, Artist =  "Eric Clapton", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Respighi:Pines of Rome", Genre = "Classical", Price = 8.99M, Artist =  "Eugene Ormandy", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Strauss: Waltzes", Genre = "Classical", Price = 8.99M, Artist =  "Eugene Ormandy", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "King For A Day Fool For A Lifetime", Genre = "Rock", Price = 8.99M, Artist =  "Faith No More", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Deixa Entrar", Genre = "Latin", Price = 8.99M, Artist =  "Falamansa", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "In Your Honor [Disc 1]", Genre = "Rock", Price = 8.99M, Artist =  "Foo Fighters", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "In Your Honor [Disc 2]", Genre = "Rock", Price = 8.99M, Artist =  "Foo Fighters", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Colour And The Shape", Genre = "Rock", Price = 8.99M, Artist =  "Foo Fighters", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bongo Fury", Genre = "Rock", Price = 8.99M, Artist =  "Frank Zappa & Captain Beefheart", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Roda De Funk", Genre = "Latin", Price = 8.99M, Artist =  "Funk Como Le Gusta", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Quanta Gente Veio Ver (Live)", Genre = "Latin", Price = 8.99M, Artist =  "Gilberto Gil", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Quanta Gente Veio ver--Bônus De Carnaval", Genre = "Jazz", Price = 8.99M, Artist =  "Gilberto Gil", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Faceless", Genre = "Metal", Price = 8.99M, Artist =  "Godsmack", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Meus Momentos", Genre = "Latin", Price = 8.99M, Artist =  "Gonzaguinha", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Nielsen: The Six Symphonies", Genre = "Classical", Price = 8.99M, Artist =  "Göteborgs Symfoniker & Neeme Järvi", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Appetite for Destruction", Genre = "Rock", Price = 8.99M, Artist =  "Guns N' Roses", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Use Your Illusion I", Genre = "Rock", Price = 8.99M, Artist =  "Guns N' Roses", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Use Your Illusion II", Genre = "Metal", Price = 8.99M, Artist =  "Guns N' Roses", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Blue Moods", Genre = "Jazz", Price = 8.99M, Artist =  "Incognito", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Matter of Life and Death", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Brave New World", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Fear Of The Dark", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live At Donington 1992 (Disc 1)", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live At Donington 1992 (Disc 2)", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Rock In Rio [CD2]", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Number of The Beast", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The X Factor", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Virtual XI", Genre = "Rock", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Real Dead One", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Real Live One", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live After Death", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "No Prayer For The Dying", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Piece Of Mind", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Powerslave", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Rock In Rio [CD1]", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Rock In Rio [CD2]", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Seventh Son of a Seventh Son", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Somewhere in Time", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Number of The Beast", Genre = "Metal", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Iron Maiden", Genre = "Blues", Price = 8.99M, Artist =  "Iron Maiden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mascagni: Cavalleria Rusticana", Genre = "Classical", Price = 8.99M, Artist =  "James Levine", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Emergency On Planet Earth", Genre = "Rock", Price = 8.99M, Artist =  "Jamiroquai", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Are You Experienced?", Genre = "Rock", Price = 8.99M, Artist =  "Jimi Hendrix", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Surfing with the Alien (Remastered)", Genre = "Rock", Price = 8.99M, Artist =  "Joe Satriani", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Jorge Ben Jor 25 Anos", Genre = "Latin", Price = 8.99M, Artist =  "Jorge Ben", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Jota Quest-1995", Genre = "Latin", Price = 8.99M, Artist =  "Jota Quest", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Living After Midnight", Genre = "Metal", Price = 8.99M, Artist =  "Judas Priest", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Weill: The Seven Deadly Sins", Genre = "Classical", Price = 8.99M, Artist =  "Kent Nagano and Orchestre de l'Opéra de Lyon", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Kiss", Genre = "Rock", Price = 8.99M, Artist =  "Kiss", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Unplugged [Live]", Genre = "Rock", Price = 8.99M, Artist =  "Kiss", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "BBC Sessions [Disc 1] [Live]", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "BBC Sessions [Disc 2] [Live]", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Coda", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Houses Of The Holy", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "In Through The Out Door", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "IV", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Led Zeppelin I", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Led Zeppelin II", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Led Zeppelin III", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Physical Graffiti [Disc 1]", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Physical Graffiti [Disc 2]", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Presence", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Song Remains The Same (Disc 1)", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Song Remains The Same (Disc 2)", Genre = "Rock", Price = 8.99M, Artist =  "Led Zeppelin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mais Do Mesmo", Genre = "Latin", Price = 8.99M, Artist =  "Legião Urbana", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits", Genre = "Reggae", Price = 8.99M, Artist =  "Lenny Kravitz", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits", Genre = "Rock", Price = 8.99M, Artist =  "Lenny Kravitz", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits", Genre = "Metal", Price = 8.99M, Artist =  "Lenny Kravitz", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Tchaikovsky: The Nutcracker", Genre = "Classical", Price = 8.99M, Artist =  "London Symphony Orchestra & Sir Charles Mackerras", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Duos II", Genre = "Latin", Price = 8.99M, Artist =  "Luciana Souza/Romero Lubambo", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chill: Brazil (Disc 1)", Genre = "Latin", Price = 8.99M, Artist =  "Marcos Valle", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Misplaced Childhood", Genre = "Rock", Price = 8.99M, Artist =  "Marillion", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Barulhinho Bom", Genre = "Latin", Price = 8.99M, Artist =  "Marisa Monte", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Szymanowski: Piano Works, Vol. 1", Genre = "Classical", Price = 8.99M, Artist =  "Martin Roscoe", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "...And Justice For All", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Black Album", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Garage Inc. (Disc 1)", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Garage Inc. (Disc 2)", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Load", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Master Of Puppets", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "ReLoad", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ride The Lightning", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "St. Anger", Genre = "Metal", Price = 8.99M, Artist =  "Metallica", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Berlioz: Symphonie Fantastique", Genre = "Classical", Price = 8.99M, Artist =  "Michael Tilson Thomas & San Francisco Symphony", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Prokofiev: Romeo & Juliet", Genre = "Classical", Price = 8.99M, Artist =  "Michael Tilson Thomas & San Francisco Symphony", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Miles Ahead", Genre = "Jazz", Price = 8.99M, Artist =  "Miles Davis", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Essential Miles Davis [Disc 1]", Genre = "Jazz", Price = 8.99M, Artist =  "Miles Davis", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Essential Miles Davis [Disc 2]", Genre = "Jazz", Price = 8.99M, Artist =  "Miles Davis", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Milton Nascimento Ao Vivo", Genre = "Latin", Price = 8.99M, Artist =  "Milton Nascimento", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Minas", Genre = "Latin", Price = 8.99M, Artist =  "Milton Nascimento", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Motley Crue Greatest Hits", Genre = "Metal", Price = 8.99M, Artist =  "Mötley Crüe", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ace Of Spades", Genre = "Metal", Price = 8.99M, Artist =  "Motörhead", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mozart: Chamber Music", Genre = "Classical", Price = 8.99M, Artist =  "Nash Ensemble", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best of Beethoven", Genre = "Classical", Price = 8.99M, Artist =  "Nicolaus Esterhazy Sinfonia", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Nevermind", Genre = "Rock", Price = 8.99M, Artist =  "Nirvana", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Compositores", Genre = "Rock", Price = 8.99M, Artist =  "O Terço", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Olodum", Genre = "Latin", Price = 8.99M, Artist =  "Olodum", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bach: The Brandenburg Concertos", Genre = "Classical", Price = 8.99M, Artist =  "Orchestra of The Age of Enlightenment", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Acústico MTV", Genre = "Latin", Price = 8.99M, Artist =  "Os Paralamas Do Sucesso", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Arquivo II", Genre = "Latin", Price = 8.99M, Artist =  "Os Paralamas Do Sucesso", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Arquivo Os Paralamas Do Sucesso", Genre = "Latin", Price = 8.99M, Artist =  "Os Paralamas Do Sucesso", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Tribute", Genre = "Metal", Price = 8.99M, Artist =  "Ozzy Osbourne", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bark at the Moon (Remastered)", Genre = "Rock", Price = 8.99M, Artist =  "Ozzy Osbourne", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Blizzard of Ozz", Genre = "Rock", Price = 8.99M, Artist =  "Ozzy Osbourne", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Diary of a Madman (Remastered)", Genre = "Rock", Price = 8.99M, Artist =  "Ozzy Osbourne", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "No More Tears (Remastered)", Genre = "Rock", Price = 8.99M, Artist =  "Ozzy Osbourne", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Speak of the Devil", Genre = "Rock", Price = 8.99M, Artist =  "Ozzy Osbourne", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Walking Into Clarksdale", Genre = "Rock", Price = 8.99M, Artist =  "Page & Plant", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Beast Live", Genre = "Rock", Price = 8.99M, Artist =  "Paul D'Ianno", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live On Two Legs [Live]", Genre = "Rock", Price = 8.99M, Artist =  "Pearl Jam", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Riot Act", Genre = "Rock", Price = 8.99M, Artist =  "Pearl Jam", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ten", Genre = "Rock", Price = 8.99M, Artist =  "Pearl Jam", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Vs.", Genre = "Rock", Price = 8.99M, Artist =  "Pearl Jam", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Dark Side Of The Moon", Genre = "Rock", Price = 8.99M, Artist =  "Pink Floyd", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits I", Genre = "Rock", Price = 8.99M, Artist =  "Queen", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits II", Genre = "Rock", Price = 8.99M, Artist =  "Queen", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "News Of The World", Genre = "Rock", Price = 8.99M, Artist =  "Queen", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "New Adventures In Hi-Fi", Genre = "Rock", Price = 8.99M, Artist =  "R.E.M.", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Raul Seixas", Genre = "Rock", Price = 8.99M, Artist =  "Raul Seixas", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "By The Way", Genre = "Rock", Price = 8.99M, Artist =  "Red Hot Chili Peppers", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Californication", Genre = "Rock", Price = 8.99M, Artist =  "Red Hot Chili Peppers", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Purcell: The Fairy Queen", Genre = "Classical", Price = 8.99M, Artist =  "Roger Norrington, London Classical Players", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Haydn: Symphonies 99 - 104", Genre = "Classical", Price = 8.99M, Artist =  "Royal Philharmonic Orchestra & Sir Thomas Beecham", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Retrospective I (1974-1980)", Genre = "Rock", Price = 8.99M, Artist =  "Rush", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Santana - As Years Go By", Genre = "Rock", Price = 8.99M, Artist =  "Santana", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Santana Live", Genre = "Rock", Price = 8.99M, Artist =  "Santana", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Supernatural", Genre = "Rock", Price = 8.99M, Artist =  "Santana", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Handel: The Messiah (Highlights)", Genre = "Classical", Price = 8.99M, Artist =  "Scholars Baroque Ensemble", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Prokofiev: Symphony No.1", Genre = "Classical", Price = 8.99M, Artist =  "Sergei Prokofiev & Yuri Temirkanov", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Wagner: Favourite Overtures", Genre = "Classical", Price = 8.99M, Artist =  "Sir Georg Solti & Wiener Philharmoniker", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Maquinarama", Genre = "Rock", Price = 8.99M, Artist =  "Skank", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "O Samba Poconé", Genre = "Rock", Price = 8.99M, Artist =  "Skank", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A-Sides", Genre = "Rock", Price = 8.99M, Artist =  "Soundgarden", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Heart of the Night", Genre = "Jazz", Price = 8.99M, Artist =  "Spyro Gyra", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Morning Dance", Genre = "Jazz", Price = 8.99M, Artist =  "Spyro Gyra", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "In Step", Genre = "Blues", Price = 8.99M, Artist =  "Stevie Ray Vaughan & Double Trouble", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Core", Genre = "Rock", Price = 8.99M, Artist =  "Stone Temple Pilots", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mezmerize", Genre = "Metal", Price = 8.99M, Artist =  "System Of A Down", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Temple of the Dog", Genre =  "Alternative", Price = 8.99M, Artist =  "Temple of the Dog", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "[1997] Black Light Syndrome", Genre = "Rock", Price = 8.99M, Artist =  "Terry Bozzio, Tony Levin & Steve Stevens", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "South American Getaway", Genre = "Classical", Price = 8.99M, Artist =  "The 12 Cellists of The Berlin Philharmonic", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live [Disc 1]", Genre = "Blues", Price = 8.99M, Artist =  "The Black Crowes", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live [Disc 2]", Genre = "Blues", Price = 8.99M, Artist =  "The Black Crowes", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Beyond Good And Evil", Genre = "Rock", Price = 8.99M, Artist =  "The Cult", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Doors", Genre = "Rock", Price = 8.99M, Artist =  "The Doors", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "English Renaissance", Genre = "Classical", Price = 8.99M, Artist =  "The King's Singers", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Police Greatest Hits", Genre = "Rock", Price = 8.99M, Artist =  "The Police", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Every Kind of Light", Genre = "Rock", Price = 8.99M, Artist =  "The Posies", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Hot Rocks, 1964-1971 (Disc 1)", Genre = "Rock", Price = 8.99M, Artist =  "The Rolling Stones", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "No Security", Genre = "Rock", Price = 8.99M, Artist =  "The Rolling Stones", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Voodoo Lounge", Genre = "Rock", Price = 8.99M, Artist =  "The Rolling Stones", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "My Generation - The Very Best Of The Who", Genre = "Rock", Price = 8.99M, Artist =  "The Who", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Serie Sem Limite (Disc 1)", Genre = "Latin", Price = 8.99M, Artist =  "Tim Maia", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Serie Sem Limite (Disc 2)", Genre = "Latin", Price = 8.99M, Artist =  "Tim Maia", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bach: Toccata & Fugue in D Minor", Genre = "Classical", Price = 8.99M, Artist =  "Ton Koopman", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Achtung Baby", Genre = "Rock", Price = 8.99M, Artist =  "U2", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "B-Sides 1980-1990", Genre = "Rock", Price = 8.99M, Artist =  "U2", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "How To Dismantle An Atomic Bomb", Genre = "Rock", Price = 8.99M, Artist =  "U2", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Pop", Genre = "Rock", Price = 8.99M, Artist =  "U2", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Rattle And Hum", Genre = "Rock", Price = 8.99M, Artist =  "U2", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best Of 1980-1990", Genre = "Rock", Price = 8.99M, Artist =  "U2", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "War", Genre = "Rock", Price = 8.99M, Artist =  "U2", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Zooropa", Genre = "Rock", Price = 8.99M, Artist =  "U2", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "UB40 The Best Of - Volume Two [UK]", Genre = "Reggae", Price = 8.99M, Artist =  "UB40", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Diver Down", Genre = "Rock", Price = 8.99M, Artist =  "Van Halen", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best Of Van Halen, Vol. I", Genre = "Rock", Price = 8.99M, Artist =  "Van Halen", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Van Halen III", Genre = "Rock", Price = 8.99M, Artist =  "Van Halen", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Van Halen", Genre = "Rock", Price = 8.99M, Artist =  "Van Halen", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Axé Bahia 2001", Genre =  "Pop", Price = 8.99M, Artist =  "Various Artists", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Sambas De Enredo 2001", Genre = "Latin", Price = 8.99M, Artist =  "Various Artists", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Vozes do MPB", Genre = "Latin", Price = 8.99M, Artist =  "Various Artists", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Contraband", Genre = "Rock", Price = 8.99M, Artist =  "Velvet Revolver", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Vinicius De Moraes", Genre = "Latin", Price = 8.99M, Artist =  "Vinícius De Moraes", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bach: Goldberg Variations", Genre = "Classical", Price = 8.99M, Artist =  "Wilhelm Kempff", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bartok: Violin & Viola Concertos", Genre = "Classical", Price = 8.99M, Artist =  "Yehudi Menuhin", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bach: The Cello Suites", Genre = "Classical", Price = 8.99M, Artist =  "Yo-Yo Ma", AlbumUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ao Vivo [IMPORT]", Genre = "Latin", Price = 8.99M, Artist =  "Zeca Pagodinho", AlbumUrl = "/Content/Images/placeholder.gif" },
            }.ForEach(a => context.Albums.Add(a));
        }
    }
}
